strategy:
  matrix:
    node-version: [18.x, 20.x]
    os: [ubuntu-latest]
  steps:
    name: Node ${{ matrix.node-version }} on ${{ matrix.os }}
    uses: actions/setup-node@v3
    uses: actions/checkout@v3
    node-version: ${{ matrix.node-version }}
  run:
    